### ISSUE TITLE
Ethernet works with latest kernel

### ISSUE THREAD

**Issue by aviallon** [nguiard/archlinux-orange-pi-zero#3]
See screenshot
![ethernet_4 17](https://user-images.githubusercontent.com/7479436/40282524-3665e5aa-5c60-11e8-96c8-7ebadf1ea631.png)

**Comment by nguiard** [comment]
Great! Thanks a lot for the heads up, and sorry for the very late reaction!

**Comment by aviallon** [comment]
Ahah no pb. Cool to see that you are still alive 😂

Le dim. 16 sept. 2018 à 10:31, Nicolas Guiard <notifications@github.com> a
écrit :
